---
# MySQL Secrets
mysql_root_password: 123456789
mysql_users:
  - name: lumisportal
    host: "%"
    password: 123456789
    priv: "lumisportal.*:ALL"

lumis_db_pass: "{{ mysql_users[0].password }}"
lumis_db_user: "{{ mysql_users[0].name }}"
